import React, { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { type LLMModel } from "../data/llms";

interface ComparisonModalProps {
  models: LLMModel[];
  onClose: () => void;
  onRemoveModel: (modelName: string) => void;
}

const costColors: Record<string, string> = {
  "Free": "bg-green-500 text-white",
  "Paid": "bg-blue-500 text-white"
};

const vendorColors: Record<string, string> = {
  "OpenAI": "text-green-400",
  "Anthropic": "text-orange-400", 
  "Google": "text-blue-400",
  "Meta": "text-purple-400",
  "Mistral AI": "text-cyan-400",
  "Cohere": "text-pink-400",
  "Perplexity": "text-indigo-400",
  "AI21 Labs": "text-teal-400",
  "Stability AI": "text-rose-400",
  "Technology Innovation Institute": "text-amber-400",
  "Zhipu AI": "text-emerald-400"
};

const comparisonRows = [
  { key: "vendor", label: "Vendor", type: "text" },
  { key: "cost", label: "Cost Tier", type: "badge" },
  { key: "category", label: "Category", type: "text" },
  { key: "releaseDate", label: "Release Year", type: "text" },
  { key: "modelSize", label: "Model Size", type: "text" },
  { key: "capabilities", label: "Key Capabilities", type: "list" },
  { key: "useCases", label: "Best Use Cases", type: "list" },
  { key: "deployment", label: "Deployment Options", type: "list" },
  { key: "summary", label: "Summary", type: "text" }
];

export function ComparisonModal({ models, onClose, onRemoveModel }: ComparisonModalProps) {
  const [showExportOptions, setShowExportOptions] = useState(false);

  // Close modal on Escape key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (showExportOptions) {
          setShowExportOptions(false);
        } else {
          onClose();
        }
      }
    };
    
    const handleClickOutside = (e: MouseEvent) => {
      if (showExportOptions && !(e.target as Element).closest('.export-dropdown')) {
        setShowExportOptions(false);
      }
    };
    
    document.addEventListener('keydown', handleEscape);
    document.addEventListener('mousedown', handleClickOutside);
    document.body.style.overflow = 'hidden';
    
    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.removeEventListener('mousedown', handleClickOutside);
      document.body.style.overflow = 'unset';
    };
  }, [onClose, showExportOptions]);

  const exportComparison = (format: 'text' | 'pdf') => {
    if (format === 'pdf') {
      exportToPDF();
    } else {
      exportToText();
    }
    setShowExportOptions(false);
  };

  const exportToText = () => {
    // Create a comprehensive comparison report
    const currentDate = new Date().toLocaleDateString();
    const comparisonReport = `
ExecLLM - AI Model Comparison Report
Generated on: ${currentDate}
Models Compared: ${models.length}

${'='.repeat(60)}

${models.map((model, index) => `
${index + 1}. ${model.name} by ${model.vendor}
${'─'.repeat(40)}
Cost Tier: ${model.cost}
Category: ${model.category || 'N/A'}
Release Year: ${model.releaseDate || 'N/A'}
Model Size: ${model.modelSize || 'N/A'}

Key Capabilities:
${model.capabilities.map(cap => `• ${cap}`).join('\n')}

Best Use Cases:
${model.useCases.map(use => `• ${use}`).join('\n')}

Deployment Options:
${model.deployment.map(dep => `• ${dep}`).join('\n')}

Summary:
${model.summary}

`).join('\n' + '='.repeat(60) + '\n')}

Report generated by ExecLLM - Executive AI Model Comparison Platform
Built with ❤️ by HumanXAI

For the latest information and interactive comparisons, visit ExecLLM.
`;

    const blob = new Blob([comparisonReport], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ExecLLM-Comparison-${models.map(m => m.name.replace(/\s+/g, '-')).join('-vs-')}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportToPDF = () => {
    // Create formatted HTML content for PDF
    const currentDate = new Date().toLocaleDateString();
    
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>ExecLLM Model Comparison Report</title>
  <style>
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      line-height: 1.4;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background: white;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      border-bottom: 3px solid #6366f1;
      padding-bottom: 20px;
    }
    .header h1 {
      color: #6366f1;
      font-size: 32px;
      margin: 0;
      font-weight: 700;
    }
    .header .subtitle {
      color: #64748b;
      font-size: 16px;
      margin: 8px 0 0 0;
    }
    .meta-info {
      background: #f8fafc;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 25px;
      border-left: 4px solid #6366f1;
      font-size: 14px;
    }
    .model-section {
      margin-bottom: 30px;
      page-break-inside: avoid;
      border: 2px solid #e2e8f0;
      border-radius: 12px;
      padding: 20px;
      background: #fefefe;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .model-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 2px solid #e2e8f0;
    }
    .model-name {
      font-size: 24px;
      font-weight: 700;
      color: #1e293b;
      margin: 0 0 5px 0;
    }
    .model-vendor {
      font-size: 16px;
      color: #6366f1;
      font-weight: 600;
    }
    .cost-badge {
      padding: 8px 16px;
      border-radius: 20px;
      font-weight: 700;
      font-size: 14px;
      color: white;
    }
    .cost-free { background: linear-gradient(135deg, #10b981, #059669) !important; }
    .cost-paid { background: linear-gradient(135deg, #3b82f6, #6366f1) !important; }
    .detail-section {
      margin: 20px 0;
    }
    .detail-title {
      font-size: 16px;
      font-weight: 700;
      color: #374151;
      margin-bottom: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 5px;
    }
    .summary-text {
      background: #f8fafc;
      padding: 15px;
      border-radius: 8px;
      font-style: italic;
      border-left: 4px solid #6366f1;
      font-size: 14px;
      line-height: 1.6;
    }
    .capability-grid, .usecase-grid, .deployment-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 8px;
      margin-top: 10px;
    }
    .capability-item, .usecase-item, .deployment-item {
      background: #f1f5f9;
      padding: 10px 12px;
      border-radius: 6px;
      font-size: 13px;
      border-left: 3px solid #6366f1;
    }
    .tech-details {
      background: #f8fafc;
      padding: 12px;
      border-radius: 6px;
      font-size: 14px;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      font-size: 12px;
      color: #64748b;
      border-top: 2px solid #e2e8f0;
      padding-top: 20px;
    }
    @media print {
      body { margin: 0; padding: 15mm; }
      .model-section { page-break-inside: avoid; margin-bottom: 20px; }
    }
    @page { margin: 1in; size: A4; }
  </style>
</head>
<body>
  <div class="header">
    <h1>ExecLLM</h1>
    <div class="subtitle">AI Model Comparison Report</div>
  </div>
  
  <div class="meta-info">
    <strong>Report Generated:</strong> ${currentDate}<br>
    <strong>Models Compared:</strong> ${models.length}<br>
    <strong>Type:</strong> Executive Business Analysis
  </div>

  ${models.map((model, index) => `
    <div class="model-section">
      <div class="model-header">
        <div>
          <h2 class="model-name">${model.name}</h2>
          <div class="model-vendor">${model.vendor}</div>
        </div>
        <div class="cost-badge cost-${model.cost.toLowerCase()}">${model.cost}</div>
      </div>

      <div class="detail-section">
        <div class="detail-title">Overview</div>
        <div class="summary-text">${model.summary}</div>
      </div>

      <div class="detail-section">
        <div class="detail-title">Key Capabilities</div>
        <div class="capability-grid">
          ${model.capabilities.map(cap => `<div class="capability-item">• ${cap}</div>`).join('')}
        </div>
      </div>

      <div class="detail-section">
        <div class="detail-title">Best Use Cases</div>
        <div class="usecase-grid">
          ${model.useCases.map(use => `<div class="usecase-item">• ${use}</div>`).join('')}
        </div>
      </div>

      <div class="detail-section">
        <div class="detail-title">Deployment Options</div>
        <div class="deployment-grid">
          ${model.deployment.map(dep => `<div class="deployment-item">• ${dep}</div>`).join('')}
        </div>
      </div>

      ${(model.category || model.releaseDate || model.modelSize) ? `
        <div class="detail-section">
          <div class="detail-title">Technical Details</div>
          <div class="tech-details">
            ${model.category ? `<strong>Category:</strong> ${model.category}<br>` : ''}
            ${model.releaseDate ? `<strong>Release Year:</strong> ${model.releaseDate}<br>` : ''}
            ${model.modelSize ? `<strong>Model Size:</strong> ${model.modelSize}` : ''}
          </div>
        </div>
      ` : ''}
    </div>
  `).join('')}

  <div class="footer">
    <p><strong>ExecLLM</strong> - Executive AI Model Comparison Platform</p>
    <p>Built with ❤️ by HumanXAI</p>
    <p>For the latest information and interactive comparisons, visit ExecLLM</p>
  </div>
</body>
</html>`;

    // Create a new window for PDF generation
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      
      // Wait for content to load, then trigger print
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          // Close the window after printing (optional)
          printWindow.onafterprint = () => {
            printWindow.close();
          };
        }, 500);
      };
    } else {
      // Fallback: download as HTML if popup is blocked
      alert('Pop-up blocked. Downloading as HTML file instead. You can open it and use Ctrl+P (Cmd+P on Mac) to save as PDF.');
      const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `ExecLLM-Comparison-Report-${models.map(m => m.name.replace(/\s+/g, '-')).join('-vs-')}-${new Date().toISOString().split('T')[0]}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const renderCellContent = (model: LLMModel, row: typeof comparisonRows[0]) => {
    const value = model[row.key as keyof LLMModel];
    
    switch (row.type) {
      case "badge":
        if (row.key === "cost") {
          return (
            <span className={`px-3 py-1 rounded-full text-sm font-bold ${costColors[value as string] || "bg-gray-500 text-white"}`}>
              {value}
            </span>
          );
        }
        return value;
      
      case "list":
        if (Array.isArray(value)) {
          return (
            <div className="space-y-1">
              {value.slice(0, 4).map((item, index) => (
                <div key={index} className="text-sm bg-slate-700/30 px-2 py-1 rounded">
                  {item}
                </div>
              ))}
              {value.length > 4 && (
                <div className="text-xs text-slate-400">+{value.length - 4} more</div>
              )}
            </div>
          );
        }
        return value;
      
      case "text":
      default:
        if (row.key === "summary") {
          return <div className="text-sm leading-relaxed">{value}</div>;
        }
        return value || "N/A";
    }
  };

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
      >
        <motion.div
          className="relative bg-gradient-to-br from-slate-800 to-slate-900 rounded-3xl shadow-2xl w-full max-w-7xl max-h-[90vh] overflow-hidden border border-slate-700/50"
          initial={{ scale: 0.9, opacity: 0, y: 20 }}
          animate={{ scale: 1, opacity: 1, y: 0 }}
          exit={{ scale: 0.9, opacity: 0, y: 20 }}
          transition={{ type: "spring", damping: 25, stiffness: 300 }}
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className="relative z-10 p-6 border-b border-slate-700/50">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-3xl font-bold bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent mb-2">
                  Model Comparison
                </h2>
                <p className="text-slate-400">
                  Comparing {models.length} AI model{models.length !== 1 ? 's' : ''} side-by-side
                </p>
              </div>
              
              <div className="flex items-center gap-3">
                <div className="relative export-dropdown">
                  <motion.button
                    onClick={() => setShowExportOptions(!showExportOptions)}
                    className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg transition-all duration-200 text-sm font-medium flex items-center gap-2"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Export
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </motion.button>

                  <AnimatePresence>
                    {showExportOptions && (
                      <motion.div
                        initial={{ opacity: 0, y: -10, scale: 0.95 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        exit={{ opacity: 0, y: -10, scale: 0.95 }}
                        className="absolute top-full right-0 mt-2 bg-slate-800/95 backdrop-blur-sm border border-slate-700/50 rounded-xl p-3 shadow-2xl z-30 min-w-48"
                      >
                        <div className="space-y-2">
                          <motion.button
                            onClick={() => exportComparison('text')}
                            className="w-full flex items-center gap-3 p-3 rounded-lg bg-slate-700/50 hover:bg-slate-600/50 text-slate-200 hover:text-white transition-all duration-200"
                            whileHover={{ scale: 1.02 }}
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                            </svg>
                            <div className="text-left">
                              <div className="font-medium">Text File</div>
                              <div className="text-xs text-slate-400">Plain text format (.txt)</div>
                            </div>
                          </motion.button>
                          
                          <motion.button
                            onClick={() => exportComparison('pdf')}
                            className="w-full flex items-center gap-3 p-3 rounded-lg bg-slate-700/50 hover:bg-slate-600/50 text-slate-200 hover:text-white transition-all duration-200"
                            whileHover={{ scale: 1.02 }}
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                            </svg>
                            <div className="text-left">
                              <div className="font-medium">Save as PDF</div>
                              <div className="text-xs text-slate-400">Opens print dialog to save PDF</div>
                            </div>
                          </motion.button>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
                
                <button
                  className="w-10 h-10 flex items-center justify-center rounded-full bg-slate-700/50 hover:bg-slate-600/50 text-slate-400 hover:text-white transition-all duration-200"
                  onClick={onClose}
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
          </div>

          {/* Comparison Table */}
          <div className="overflow-auto max-h-[calc(90vh-120px)]">
            <table className="w-full">
              <thead className="sticky top-0 bg-slate-800/95 backdrop-blur-sm border-b border-slate-700/50">
                <tr>
                  <td className="p-4 font-medium text-slate-300 w-48">Attribute</td>
                  {models.map((model) => (
                    <td key={model.name} className="p-4 min-w-80">
                      <div className="flex items-center justify-between">
                        <div>
                          <h3 className="text-lg font-bold text-white mb-1">{model.name}</h3>
                          <p className={`text-sm font-medium ${vendorColors[model.vendor] || "text-slate-400"}`}>
                            {model.vendor}
                          </p>
                        </div>
                        <button
                          onClick={() => onRemoveModel(model.name)}
                          className="p-1 text-slate-400 hover:text-red-400 transition-colors"
                          title="Remove from comparison"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      </div>
                    </td>
                  ))}
                </tr>
              </thead>
              
              <tbody>
                {comparisonRows.map((row, rowIndex) => (
                  <tr 
                    key={row.key}
                    className={`border-b border-slate-700/30 ${rowIndex % 2 === 0 ? 'bg-slate-800/20' : 'bg-slate-800/10'}`}
                  >
                    <td className="p-4 font-medium text-slate-300 bg-slate-800/30">
                      {row.label}
                    </td>
                    {models.map((model) => (
                      <td key={`${model.name}-${row.key}`} className="p-4 text-slate-200 align-top">
                        {renderCellContent(model, row)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Footer */}
          <div className="p-4 border-t border-slate-700/50 bg-slate-800/30">
            <div className="flex items-center justify-between text-sm text-slate-400">
              <div>
                Use checkboxes on model cards to add/remove models from comparison
              </div>
              <div>
                Press <kbd className="px-2 py-1 bg-slate-700 rounded text-xs">ESC</kbd> to close
              </div>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}